### PR TITLE
Added a search bar to resource-packs.html

### PR DESCRIPTION
**Pull request by MDxWARRIORxOP**

### CODE REVIEW

**Review by NiceygyLive — CHANGES_REQUESTED** [review]
You`ve made a typo in the html, but get that sorted and ill push it in! (i dont know how to fix it from here 😅)

**Comment by TheAlienDoctor** [comment]
This will stay open for a little longer whilst I do some research trying to figure out if there is a way to improve the search, namely the weird spacing :)

@NiceygyLive check the forked repo GitHub pages to see what I mean.

**Comment by MDxWARRIORxOP** [comment]
What typo? @NiceygyLive

**Comment by NiceygyLive** [comment]
@MDxWARRIORxOP

**Comment by TheAlienDoctor** [comment]
Red = removed
Gree = added

There is no typo there.

**Comment by NiceygyLive** [comment]
Ooh I stupid 😃.

**Comment by MDxWARRIORxOP** [comment]
Ohhh, that's probably because of my vscode formatter (prettier)

**Comment by NiceygyLive** [comment]
All good to merge?

**Comment by MDxWARRIORxOP** [comment]
wait this no merge?

**Comment by MDxWARRIORxOP** [comment]
this very outdated
ill just have to do it again

**Pull request closed without merging**
